version: '3'
services:
  glpk:
    container_name: glpk-solver
    stdin_open: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/code
  execution:
    build:
      context: .
    command: python investidor.py 


  # python:
  #   depends_on:
  #   - glpk
  #   command: python investidor.py
