version: '3'
services:
  glpk:
    container_name: glpk-solver
    stdin_open: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: python investidor.py 
    volumes:
      - .:/code    