version: '3'
services:
  glpk:
    container_name: glpk-solver
    stdin_open: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: python arquivos_professor/maximum_divesrity/maximus_diversity_transporte.py 
    # command: python arquivos_professor/caminhos_minimos/transporte_binario/transporte_binario_max.py
    volumes:
      - .:/code
      - glpk-data:/data
volumes:
  glpk-data: