version: '3'
services:
  web:
    build: . 
    #   context: .
    #   dockerfile: ./Dockerfile 
    # command: >
    #             sh -c "
    #             pip install pyomo &&
    #             python .\main.py
    #             "