version: '3'
services:
  glpk:
    container_name: glpk-solver
    stdin_open: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: python arquivos_professor/problema_mochila/mochila.py 
    volumes:
      - .:/code
      - glpk-data:/data
volumes:
  glpk-data: