version: '3'
services:
  glpk:
    container_name: glpk-solver
    stdin_open: true
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: python exercicios/caixeiro_viajante/caixeiro.py
    # command: python exercicios/caixeiro_viajante/caixeiro_max.py
    # command: python exercicios/knapsack_problem/mochila_max.py
    # command: python exercicios/condominios_estradas/cobertura_vertices.py
    # command: python exercicios/big-m/big-m.py
    # command: python exercicios/maximum_divesrity/maximus_diversity_transporte.py 
    # command: python exercicios/caminhos_minimos/transporte_binario/transporte_binario_max.py
    volumes:
      - .:/code
      - glpk-data:/data
volumes:
  glpk-data: